### ISSUE TITLE
evaluate integration with SpringAI

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/langgraph4j#15]
* Evaluate evaluate integration with [Spring AI]
* Evaluate to provide langgraph4j playground using  [Spring AI].

[Spring AI]: https://spring.io/projects/spring-ai

**Comment by hujianming8163** [comment]
@bsorrentino SpringAI and langchain4j have many similar functions with each other, and  langgraph4j depend on langchain4j, and how to process this

**Comment by bsorrentino** [comment]
> @bsorrentino SpringAI and langchain4j have many similar functions with each other, and langgraph4j depend on langchain4j, and how to process this

@hujianming8163  that's is not correct, langgraph4j has  exclusively a strategic dependency with langchain4j, there aren't its dependencies  into core implementation

**Comment by CodingNowPls** [comment]
i also want to know how to use in spring ai ,thx

**Comment by CodingNowPls** [comment]
> > @bsorrentino SpringAI and langchain4j have many similar functions with each other, and langgraph4j depend on langchain4j, and how to process thisSpringAI 和 langchain4j 有很多相似的功能，langgraph4j 依赖于 langchain4j，以及如何处理
> 
> @hujianming8163 that's is not correct, langgraph4j has exclusively a strategic dependency with langchain4j, there aren't its dependencies into core implementation这是不正确的，LangGraph4j 与 LangChain4j 完全具有战略依赖关系，没有它对核心实现的依赖关系

i also want to know how to use in spring ai ,thx

**Comment by bsorrentino** [comment]
Hi @hujianming8163 in folder [samples/springai-agentexecutor](https://github.com/bsorrentino/langgraph4j/tree/main/samples/springai-agentexecutor) there is an implementation of **Agent Executor** using Langgraph4j and SpringAI

**Comment by CodingNowPls** [comment]
> Hi @hujianming8163 in folder [samples/springai-agentexecutor](https://github.com/bsorrentino/langgraph4j/tree/main/samples/springai-agentexecutor) there is an implementation of **Agent Executor** using Langgraph4j and SpringAI

thx
