### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by TyCoding** [bsorrentino/langgraph4j#30]
Hi langgraph4j, I used the following configuration to build the Graph process. After executing it, I found that there was an extra empty "stop" node in the Mermaid graph. Why is this?

In addition, is it necessary to use `.addEdge(StateGraph.START, "node1")` for each graph start node? Because when I use `.addEdge("start", "node1")`, I get an error `missing Entry Point`

```java
public static void main(String[] args) throws Exception {
        AsyncNodeAction<State> node1 = AsyncNodeAction.node_async(state -> {
            log.info("Node1, {}", state);
            return CollectionsUtils.mapOf("Node1Key", "Node1Val");
        });
        AsyncNodeAction<State> node2 = AsyncNodeAction.node_async(state -> {
            log.info("Node2, {}", state);
            return CollectionsUtils.mapOf("Node2Key", "Node2Val");
        });

        StateGraph<State> stateStateGraph = new StateGraph<>(State::new)
                .addEdge(StateGraph.START, "node1")
                .addNode("node1", node1)
                .addEdge("node1", "node2")
                .addNode("node2", node2)
                .addEdge("node2", StateGraph.END)
                ;

        CompiledGraph<State> app = stateStateGraph.compile();
        GraphRepresentation result = app.getGraph(GraphRepresentation.Type.MERMAID);

        AsyncGenerator<NodeOutput<State>> stream = app.stream(Map.of("start", "Start Param"));
        stream.forEach(i -> {
            log.info("%%%% node={}, state={}", i.node(), i.state());
        });

        System.out.println(result.getContent());
    }
```

<img width="464" alt="image" src="https://github.com/user-attachments/assets/1cf6acfb-d9ac-4be4-903b-beb42ac30d6c">

**Comment by TyCoding** [comment]
In addition, there is another very important question. For example, some llm worflows products use streaming response to output llm results when executing LLM nodes. So, when using langgraph, is there a way to execute LLM nodes and output LLM contents in a streaming manner at the same time?

**Comment by bsorrentino** [comment]
> Hi langgraph4j, I used the following configuration to build the Graph process. After executing it, I found that there was an extra empty "stop" node in the Mermaid graph. Why is this?
> 
> In addition, is it necessary to use `.addEdge(StateGraph.START, "node1")` for each graph start node? Because when I use `.addEdge("start", "node1")`, I get an error `missing Entry Point`
> 
> ```java
> public static void main(String[] args) throws Exception {
>         AsyncNodeAction<State> node1 = AsyncNodeAction.node_async(state -> {
>             log.info("Node1, {}", state);
>             return CollectionsUtils.mapOf("Node1Key", "Node1Val");
>         });
>         AsyncNodeAction<State> node2 = AsyncNodeAction.node_async(state -> {
>             log.info("Node2, {}", state);
>             return CollectionsUtils.mapOf("Node2Key", "Node2Val");
>         });
> 
>         StateGraph<State> stateStateGraph = new StateGraph<>(State::new)
>                 .addEdge(StateGraph.START, "node1")
>                 .addNode("node1", node1)
>                 .addEdge("node1", "node2")
>                 .addNode("node2", node2)
>                 .addEdge("node2", StateGraph.END)
>                 ;
> 
>         CompiledGraph<State> app = stateStateGraph.compile();
>         GraphRepresentation result = app.getGraph(GraphRepresentation.Type.MERMAID);
> 
>         AsyncGenerator<NodeOutput<State>> stream = app.stream(Map.of("start", "Start Param"));
>         stream.forEach(i -> {
>             log.info("%%%% node={}, state={}", i.node(), i.state());
>         });
> 
>         System.out.println(result.getContent());
>     }
> ```
> 
> <img alt="image" width="464" src="https://private-user-images.githubusercontent.com/36946717/367551392-1cf6acfb-d9ac-4be4-903b-beb42ac30d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzOTQ0MTksIm5iZiI6MTcyNjM5NDExOSwicGF0aCI6Ii8zNjk0NjcxNy8zNjc1NTEzOTItMWNmNmFjZmItZDlhYy00YmU0LTkwM2ItYmViNDJhYzMwZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDA5NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YTljYzUxNzRiZmUwMzM1MGZjYjQ5YTYwODYxMGQ1ZjZhNTdhMTljZGI5MTYyNTMwYWFkODlkZmUwMjFkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JVTaD3R0bzVFgWDQb8el6dtmvAIm9ngL5nkNMTfe1K4">

Hi @TyCoding, in the last `1.0-SNAPSHOT`  there is a fix, please try out and let me know

**Comment by bsorrentino** [comment]
> In addition, there is another very important question. For example, some llm worflows products use streaming response to output llm results when executing LLM nodes. So, when using langgraph, is there a way to execute LLM nodes and output LLM contents in a streaming manner at the same time?
> 
> That is, when I build LLM Node, I want to use langchain4j's `StreamingChatLanguageModel` instead of `ChatLanguageModel`

Currently it is not possible yet, I've opened the #31 to keep track the request

**Comment by TyCoding** [comment]
@lordofthejars 

Thank you for your reply. I am actually considering using front-end products such as `react-flow` to design workflows visualization and using langgraph as the back-end flow support, but I am not sure whether langgraph can do this at present.

Because I am from China, I know some related llm agent worflows products: 
- [dify](https://dify.ai/)   
- [coze](https://www.coze.com)

Is the application scenario of langgrap similar to the above products?

**Comment by lordofthejars** [comment]
Hi I think you named me by error :)

**Comment by TyCoding** [comment]
> lordofthejars

Haha, I'm so sorry!

**Comment by bsorrentino** [comment]
> @bsorrentino
> 
> Thank you for your reply. I am actually considering using front-end products such as `react-flow` to design workflows visualization and using langgraph as the back-end flow support, but I am not sure whether langgraph can do this at present.
> 
> Because I am from China, I know some related llm agent worflows products:
> 
> * [dify](https://dify.ai/)
> * [coze](https://www.coze.com)
> 
> Is the application scenario of langgrap similar to the above products?

The goal of project is to bring Langgraph.js ( by langchain.ai  ) in Java eco-system as a completion of langchain4j initiative.
What you'd want to do is a great idea and,  if java is a constraint,  should be feasible combining langgraph4j + langchain4j

**Comment by 243006306** [comment]
> > @bsorrentino
> > 谢谢回复，我其实正在考虑用前端产品比如`react-flow`来设计工作流可视化，用langgraph来做后端流程支持，不过目前还不确定langgraph能不能做到这一点。
> > 因为我来自中国，所以我知道一些相关的 llm agent worflows 产品：
> > 
> > * [化解](https://dify.ai/)
> > * [科泽](https://www.coze.com)
> > 
> > langgrap的应用场景和上面的产品类似吗？
> 
> 该项目的目标是将 Langgraph.js（由 langchain.ai 开发）引入 Java 生态系统，作为 langchain4j 计划的补充。 您想要做的是一个好主意，如果 Java 是一个限制因素，那么结合 langgraph4j + langchain4j 应该是可行的



> > @bsorrentino
> > Thank you for your reply. I am actually considering using front-end products such as `react-flow` to design workflows visualization and using langgraph as the back-end flow support, but I am not sure whether langgraph can do this at present.
> > Because I am from China, I know some related llm agent worflows products:
> > 
> > * [dify](https://dify.ai/)
> > * [coze](https://www.coze.com)
> > 
> > Is the application scenario of langgrap similar to the above products?
> 
> The goal of project is to bring Langgraph.js ( by langchain.ai ) in Java eco-system as a completion of langchain4j initiative. What you'd want to do is a great idea and, if java is a constraint, should be feasible combining langgraph4j + langchain4j

Yes, it can be fully implemented by pre-coding the implementations of various nodes (such as model requests, RAG, rerank models), and then passing the JSON workflow information and parameters of each node to the front-end. Subsequently, based on these configurations, the classes of Langgraph can be instantiated. However, there is a downside: langchain4j will soon upgrade the JDK baseline to JDK 17, which may affect subsequent integrations. Personally, I'm still using JDK 8, which can be quite frustrating.

**Comment by bsorrentino** [comment]
> Yes, it can be fully implemented by pre-coding the implementations of various nodes (such as model requests, RAG, rerank models), and then passing the JSON workflow information and parameters of each node to the front-end. Subsequently, based on these configurations, the classes of Langgraph can be instantiated. However, there is a downside: langchain4j will soon upgrade the JDK baseline to JDK 17, which may affect subsequent integrations. Personally, I'm still using JDK 8, which can be quite frustrating.
 
@TyCoding  I agree on your overall approach to the problem and suggest you to move on java 17 at least as runtime (JVM). This will guarantee you for the future. I've done the same for langgraph4j.
