### ISSUE TITLE
FEAT: Use streaming response to output llm results

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/langgraph4j#31]
Related to this [question](https://github.com/bsorrentino/langgraph4j/issues/30#issuecomment-2351258641) in #30 

Enable the possibility to use the  langchain4j's `StreamingChatLanguageModel`  instead of `ChatLanguageModel`

**Comment by TyCoding** [comment]
Hi, is there any progress on this issue? Or, if a non-serializable object needs to be injected into a node in Worflows, such as WebSocket, SseEmitter, etc., which are all non-serializable, but the content needs to be pushed to the outside in real time during the execution of the node, is there any other solution?

**Comment by bsorrentino** [comment]
> Hi, is there any progress on this issue? Or, if a non-serializable object needs to be injected into a node in Worflows, such as WebSocket, SseEmitter, etc., which are all non-serializable, but the content needs to be pushed to the outside in real time during the execution of the node, is there any other solution?

Currently  to implement such feature we have to consider that :

1. `NodeAction` should be able to return an  `AsyncIterator`.
1. `NodeAction` should accept another argument (ie RunnableConfig) to decide if or not use streaming as result.
1.  connects the AsyncStream to the LLM streaming result, that in case of langchain4j is `StreamingResponseHandler`.
1.  propagate the node streaming result over graph streaming execution

It is not so simple and, potentially, could break backward compatibility so I'm evaluating the best strategy before start implementation

**Comment by TyCoding** [comment]
@bsorrentino Thanks, looking forward to this feature

**Comment by sharfy** [comment]
up

**Comment by bsorrentino** [comment]
HI @TyCoding, @sharfy The LLM streaming support for **langchain4j** has been added to last `1.0-SNAPSHOT` release

A reference implementation is [here](https://github.com/bsorrentino/langgraph4j/tree/develop/samples/agent-executor). Please take the opportunity to try it and let me know, in the meanwhile I'll document the new feature
