### ISSUE TITLE
Example AdaptiveRag issues

### ISSUE THREAD

**Issue by ribrewguy** [bsorrentino/langgraph4j#32]
I converted the AdaptiveRag example to kotlin, an although it appears to mostly work, the aregs do not seem to be passed to the service. Here is the code for [the answer grader](https://github.com/bsorrentino/langgraph4j/blob/main/adaptive-rag/src/main/java/dev/langchain4j/adaptiverag/AnswerGrader.java):

```
@Component
class AnswerGrader(
    private val chatLanguageModel: ChatLanguageModel,
) : Function<AnswerGrader.Arguments, AnswerGrader.Score> {
    private val log = KotlinLogging.logger { }

    /**
     * Binary score to assess answer addresses question.
     */
    @JvmInline
    value class Score(
        @Description("Answer addresses the question, 'yes' or 'no' (lowercase)")
        val binaryScore: String,
    ) {
        fun value(): String = binaryScore.lowercase()
    }

    @StructuredPrompt("User question: \\n\\n {question} \\n\\n LLM generation: {generation}")
    data class Arguments(
        val question: String,
        val generation: String,
    )

    interface Service {
        @SystemMessage(
            """You are a grader assessing whether the generated answer (called the generation) addresses and/or resolves the question. \\nGive a binary score 'yes' or 'no'. 'yes' means that the answer resolves the question.""",
        )
        fun invoke(userMessage: String): Score
    }

    override fun apply(args: Arguments): Score {
        log.debug { "Grading answer for args: $args" }
        val service = AiServices.create(Service::class.java, chatLanguageModel)
        val prompt = StructuredPromptProcessor.toPrompt(args)
        log.debug { "Prompt: ${prompt}" }
        val result = service.invoke(prompt.text())
        log.debug { ("Graded answer: ${result.value()}") }
        return result
    }
}
```

The service invocation always responds with the graded answer: `Understood. Please provide the specific question and the generated answer for evaluation.`. It seems to get the prompt, but not the values.

**Comment by ribrewguy** [comment]
I was able to fix this, but I think there is an underlying issue. I had updated the example to use gpt-4o instead of gpt-3.5-turbo-0125. I reverted to 3.5 and it works as expected. What is wrong with the 4o integration that the model wouldn't have any idea about incoming arguments?

**Comment by bsorrentino** [comment]
Hi @ribrewguy thanks for feedbacks

I'll arrange a notebook to test this "weird" condition

**Comment by bsorrentino** [comment]
Hi @ribrewguy 

I've created this [notebook](https://github.com/bsorrentino/langgraph4j/blob/main/how-tos/adaptiverag.ipynb) to test issue, and I've figure out that there was an error in `StructuredPrompt` format that needs of double bracket `{{ .... }}`

**Comment by ribrewguy** [comment]
Thanks for the quick response! I made the updates locally and while it works better now, it produces unexpected results. This is what I logged: 

```
Prompt: Prompt { text = "User question: \n\n What player at the Bears expected to draft first in the 2024 NFL draft? \n\n LLM generation: The Bears selected USC quarterback Caleb Williams with the No. 1 pick in the 2024 NFL Draft." }
[DEBUG] i.r.p.AnswerGrader - Graded answer: no
```

The generation definitely seems to address the user question. Could GPT 4o be that much worse at making this type of determination than 3.5-turbo?

**Comment by bsorrentino** [comment]
@ribrewguy I don't believe that GPT4o is worse

However  take a look to this [notebook](https://github.com/bsorrentino/langgraph4j/blob/develop/how-tos/adaptiverag.ipynb), at the end I've added your sample and using `gpt-4o-mini` works 🤔
