### ISSUE TITLE
About Version

### ISSUE THREAD

**Issue by TyCoding** [bsorrentino/langgraph4j#33]
Hi, the 1.0-beta5 version does not seem to be released to Maven Central. Secondly, how can I use the 1.0-SNAPSHOT version?

**Comment by bsorrentino** [comment]
Hi @TyCoding 

The deployment process has been completed with success and the artifacts are on [Sonatype Repo](https://repo1.maven.org/maven2/org/bsc/langgraph4j/langgraph4j-core-jdk8/). 

Probably there are some issues  with synchronization between Sonatype and Mvnrepository
